Repository Typing-Monkeys/AppuntiUniversita, pull requests merged in 2023-07, with the labels that each got.

#39 feat(actions): Auto Tag and Release
  .github/workflows/autorelease.yml
Labels: actions

#44 feat: LICENSE
  LICENSE
Labels: proposta

#37 feat(appunti): Advanced and Distributed Algorithm Pinotti
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/README.md
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/bipartite1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/bipartite2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/bipartite3.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/bipartite4.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/bipartite5.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex3.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex4.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex5.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex6.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex7.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex8.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/ex9.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/flow1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/flow2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/flow3.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/flow4.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/hirschberg.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/linear_least.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/linear_least2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/matrix1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/matrix2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/matrixmultiplication.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/opt_recursion_tree.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/pathological_example.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/pole1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/pole2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/pole3.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/pole4.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/rna1.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/rna2.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/rna3.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/rna4.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/sa.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/seq_align_recurrence.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/seqalignmatrix.png
  magistrale/Anno 1/Advanced and Distributed Algorithms/Pinotti/imgs/zaino1.png
Labels: nuovo materiale

#50 feat(actions): Migliorata Auto Tag & Release
  .github/workflows/autorelease.yml
  .github/workflows/configs/conf.toml
Labels: actions

#49 feat(actions): aggiunta action Run LaTex Checks on PR
  .github/workflows/configs/ltex.json
  .github/workflows/prlinter.yml
Labels: proposta, actions
