Repository Typing-Monkeys/AppuntiUniversita, pull requests merged in 2023-10, with the labels that each got.

#64 feat(progetti): Aggiunto progetto Simulazione
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/Progetto_Simulazione_McFit_Posta_Romani.pdf
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/mcfit.ods
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/mcfit_30.pdf
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/mcfit_50.pdf
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/mcfit_arena.doe
  magistrale/Anno 2/Simulazione/progetti/SimulazionePalestra/parametri_teorici.ods
Labels: nuovo materiale, ready

#70 refactor: Eliminati file vecchi
  triennale/Anno 2/Algoritmi/Pinotti.docx
Labels: ready

#68 chore: Aggiunto .gitattributes
  .gitattributes
Labels: ready

#67 feat(appunti): Aggiunti appunti di Linguaggi Formali e Compilatori
  triennale/Anno 2/Linguaggi Formali e Compilatori/Le Vicende Di Carpi.pdf
  triennale/Anno 2/Linguaggi Formali e Compilatori/Specchietto Generale Linguaggi.pdf
  triennale/Anno 2/Linguaggi Formali e Compilatori/dispense del prof/dispense_carpi.pdf
  triennale/Anno 2/Linguaggi Formali e Compilatori/dispense del prof/ecodispensa_carpi.pdf
  triennale/Anno 2/Linguaggi/Le Vicende Di Carpi.pdf
  triennale/Anno 2/Linguaggi/dispensa.pdf
Labels: nuovo materiale, ready

#65 feat(appunti): Aggiunti appunti Diritto dell'Informatica
  triennale/Anno 2/Diritto/FloridoFlorindi/Diritto Appunti.pdf
  triennale/Anno 2/Diritto/FloridoFlorindi/README.md
Labels: nuovo materiale, ready

#66 feat(appunti): Aggiunti appunti Architettura Reti
  triennale/Anno 3/Architettura Reti/Architettura Reti Appunti.pdf
Labels: nuovo materiale, ready

#55 feat(appunti): Appunti di calcolo numerico
  triennale/Anno 2/Calcolo Numerico/CalcNum-merged.md
  triennale/Anno 2/Calcolo Numerico/CalcNum-merged.pdf
  triennale/Anno 2/Calcolo Numerico/argomenti/0. Introduzione.md
  triennale/Anno 2/Calcolo Numerico/argomenti/1. Stabilità numerica.md
  triennale/Anno 2/Calcolo Numerico/argomenti/2. Error Analysis.md
  triennale/Anno 2/Calcolo Numerico/argomenti/3. Errore Per Le Funzioni Razionali.md
  triennale/Anno 2/Calcolo Numerico/argomenti/4. Problemi Ben Posti.md
  triennale/Anno 2/Calcolo Numerico/argomenti/5. Derivata di più variabili.md
  triennale/Anno 2/Calcolo Numerico/argomenti/6. Valutazione di un polinomio.md
  triennale/Anno 2/Calcolo Numerico/argomenti/7. Vettori.md
  triennale/Anno 2/Calcolo Numerico/argomenti/8. Matrici.md
  triennale/Anno 2/Calcolo Numerico/argomenti/9. Altre Strutture.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a0. Sistemi lineari.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a1. Algoritmo di Gauss.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a2. Matrici tridiagonali.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a3. Fattorizzazione LU.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a3a. Esercizio.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a4. Variante del Massimo Pivot Parziale (GEPP).md
  triennale/Anno 2/Calcolo Numerico/argomenti/a5. Curva di Bezier.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a6. Modello della corda elastica.md
  triennale/Anno 2/Calcolo Numerico/argomenti/a7. Interpolazione.md
Labels: nuovo materiale
